#!/bin/bash
export REPO=$PWD/repo
export REPO_TEST=$PWD/test
rm $REPO/*jar
rm $REPO_TEST/*jar

$ECLIPSE_HOME/eclipse -debug -consolelog -nosplash -verbose -application org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher -metadataRepository file://$REPO -artifactRepository file://$REPO -source $REPO -compress -publishArtifacts
$ECLIPSE_HOME/eclipse -debug -consolelog -nosplash -verbose -application org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher -metadataRepository file://$REPO_TEST -artifactRepository file://$REPO_TEST -source $REPO_TEST -compress -publishArtifacts
